import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import '../../../providers/app_providers.dart';
import '../../../models/coach_note.dart';
import '../../../theme/app_colors.dart';
import '../../../theme/app_typography.dart';
import '../../../theme/app_spacing.dart';
import '../../../widgets/surface_card.dart';
import '../../../widgets/async_error_card.dart';
import '../../../widgets/app_bottom_sheet.dart';

class CoachNotesCard extends ConsumerWidget {
  const CoachNotesCard({super.key});

  void _showHistory(BuildContext context, WidgetRef ref) {
    final account = ref.read(activeAccountIdProvider);
    showAppBottomSheet(
      context: context,
      builder: (context) => Consumer(
        builder: (context, ref, _) {
          final changed =
              ref.watch(accountTransitionProvider) ||
              ref.watch(activeAccountIdProvider) != account;
          final history = changed
              ? const <CoachNote>[]
              : ref.watch(coachHistoryProvider);
          return AppSheet(
            title: 'Coach History',
            titleAction: IconButton(
              tooltip: 'Close coach history',
              onPressed: () => Navigator.of(context).pop(),
              icon: const Icon(Icons.close_rounded),
            ),
            maxHeightFactor: 0.6,
            child: changed
                ? const Text(
                    'Your account changed. Close this sheet to continue.',
                  )
                : history.isEmpty
                ? const Text('No coach notes saved yet.')
                : Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      for (final note in history) ...[
                        Padding(
                          padding: const EdgeInsets.symmetric(vertical: 12),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                DateTime.tryParse(note.date) != null
                                    ? DateFormat(
                                        'MMM d, yyyy',
                                      ).format(DateTime.parse(note.date))
                                    : note.date,
                                style: context.text.caption.copyWith(
                                  color: context.colors.accentText,
                                ),
                              ),
                              const SizedBox(height: 8),
                              Text(note.note, style: context.text.body),
                              if (note.isAi) ...[
                                const SizedBox(height: 6),
                                Text(
                                  'Generated by AI',
                                  style: context.text.micro,
                                ),
                              ],
                            ],
                          ),
                        ),
                      ],
                    ],
                  ),
          );
        },
      ),
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final note = ref.watch(coachNoteProvider);
    final profile = ref.watch(profileProvider);
    final feedback = ref.watch(coachNoteFeedbackProvider);
    final outdated = ref.watch(coachNoteOutdatedProvider);
    final waiting =
        ref.watch(accountTransitionProvider) ||
        ref.watch(accountHydratingProvider);
    final selected = DateTime.parse(ref.watch(dateStringProvider));
    final now = ref.watch(clockProvider);
    final future = selected.isAfter(DateTime(now.year, now.month, now.day));
    final busy = note.isLoading || feedback.refreshing;
    void refresh() =>
        ref.read(coachNoteProvider.notifier).fetchNote(force: true);

    return SurfaceCard(
      onTap: () => _showHistory(context, ref),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                width: 32,
                height: 32,
                decoration: BoxDecoration(
                  color: context.colors.primary,
                  borderRadius: BorderRadius.circular(Radii.chip),
                ),
                child: Icon(
                  Icons.sports_rounded,
                  color: context.colors.onPrimary,
                  size: 18,
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Text(
                  profile.coachDisplayName,
                  style: context.text.cardTitle.copyWith(
                    color: context.colors.accentText,
                  ),
                ),
              ),
              if (!future)
                IconButton(
                  tooltip: busy ? 'Updating coach note' : 'Refresh coach note',
                  onPressed: busy || waiting ? null : refresh,
                  icon: busy
                      ? const SizedBox(
                          width: 18,
                          height: 18,
                          child: CircularProgressIndicator(strokeWidth: 2),
                        )
                      : Icon(
                          Icons.refresh_rounded,
                          color: context.colors.accentText,
                          size: 20,
                        ),
                ),
            ],
          ),
          const SizedBox(height: 16),
          note.when(
            data: (value) => Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(value.note, style: context.text.body),
                const SizedBox(height: 12),
                Text(
                  value.isAi ? 'Generated by AI' : 'Coach note',
                  style: context.text.micro.copyWith(
                    color: context.colors.textMedium,
                  ),
                ),
              ],
            ),
            loading: () =>
                Text('Coach is writing...', style: context.text.body),
            error: (_, _) => AsyncErrorCard(
              title: 'Coach note unavailable',
              message: 'Your note could not be loaded. Please try again.',
              actionText: 'Retry',
              onRetry: waiting || future ? null : refresh,
            ),
          ),
          if (!busy && feedback.message != null) ...[
            const SizedBox(height: 8),
            Text(feedback.message!, style: context.text.caption),
          ] else if (!busy && outdated && !future) ...[
            const SizedBox(height: 8),
            Text(
              'Records may have changed. Refresh for an updated note.',
              style: context.text.caption.copyWith(
                color: context.colors.textMedium,
              ),
            ),
          ],
        ],
      ),
    );
  }
}
